classifications
  - Binary
  - multi class
  - sentiment analysis
  - Anomly detection
Regression
Recommender systems
Reinforcement learning
NLP
    - Q&A
    - Auto comletion
    -chatbot
vision
  -object detection
   - object detection
   - image classification
   -image tagging
Data
   -numerical data
    -image data
    -audion data
    -video data
    -text data
    -from documents
    -satelite imagery
    -timeseries data(temperature regarding)

what are csv,tsv files?
what are packages available to handle csv data?
what is json format?
how to handle json data?
what are packages avilable in image data?
what are packages avilable in audio data?
with all the packages above check how to read the data?
how to display the same data?


1.what are csv files?
->A comma-separated values file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. The use of the comma as a field separator is the source of the name for this file format.


2.what are tsv files?
->A tab-separated values file is a simple text format for storing data in a tabular structure, e.g., database table or spreadsheet data, and a way of exchanging information between databases. Each record in the table is one line of the text file.



In [4]:
replace comma in the file sample.csv with tab and store it in a file as tsv format
input: A csv file
output: it is a tsv fil

SyntaxError: invalid syntax (<ipython-input-4-e81c4980e561>, line 1)

In [7]:
out = [3,32,23]

In [8]:
# replace the multiples of 3 in 1
out1 = [i if i%3!=0 else -1 for i in out]
out1

[-1, 32, 23]

In [9]:
out.extend([3,2,5,7])

In [10]:
out

[3, 32, 23, 3, 2, 5, 7]

In [12]:
# replace multiples of 2 with -2
# replace multiplles of 3 with -1
# if it is a multiple of both replace with -2
out1 = []
for i in out:
    if i%2==0:
        out1.append(-2)
    elif i%3 == 0:
        out1.append(-1)
    else:
        out1.append(i)
print(out1)
print(out)
        

[-1, -2, 23, -1, -2, 5, 7]
[3, 32, 23, 3, 2, 5, 7]


In [13]:
out1 = []
for i in out:
    if i%2==0:
        out1.append(-2)
    elif i%3 == 0:
        out1.append(-1)
    else:
        out1.append(i)
print(out1)
print(out)
out2 = [-2 if i%2==0 else -1 if i%3==0 else i for i in out]
print(out2)

[-1, -2, 23, -1, -2, 5, 7]
[3, 32, 23, 3, 2, 5, 7]
[-1, -2, 23, -1, -2, 5, 7]


### list comprehension with nested for

In [15]:
l1 = ([4,3,5,6])

l2 = ([3,2,6,7])

In [16]:
l2 = ([3,2,6,7])

In [17]:
l1


[4, 3, 5, 6]

In [18]:
numbers = [(i,j) for i in l1 for j in l2]
numbers

[(4, 3),
 (4, 2),
 (4, 6),
 (4, 7),
 (3, 3),
 (3, 2),
 (3, 6),
 (3, 7),
 (5, 3),
 (5, 2),
 (5, 6),
 (5, 7),
 (6, 3),
 (6, 2),
 (6, 6),
 (6, 7)]

 l2 =[[23,34],[34,42],[65,24]]

In [19]:
l2 =[[23,34],[34,42],[65,24]]
out2 = [i for j in l2 for i in j]
out2

[23, 34, 34, 42, 65, 24]

In [21]:
# common element in two lists using list comprehension
l3 = list(range(5,20,2))
l4 = list(range(1,20,2))
print(l3,l4)
[i for i in l3 for j in l4 if i==j]

[5, 7, 9, 11, 13, 15, 17, 19] [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


[5, 7, 9, 11, 13, 15, 17, 19]

## Numpy
 - numerical python
 - vectorised programming
 - handling multidimensional data
 - manipulating Arrays
 - we can define the datatype
 - commonly used with numeric data we can use mixed data as well
  - faster execution
  -

In [22]:
# version
import numpy
numpy.__version__

'1.16.5'

In [23]:
# importing a package with alias name
import numpy as np

In [25]:
l = [8,5,7,3,4]
array_ld = np.array(l)
print(type(array_ld))
print(array_ld)


<class 'numpy.ndarray'>
[8 5 7 3 4]


In [28]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [29]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [30]:
np.diag([1,3,2])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 2]])

In [33]:
# creating arrays in specific range
print(np.arange(6))

[0 1 2 3 4 5]


In [ ]:
7036736992