In [2]:
#vectorize functions

In [3]:
L = [23,45,-23,67,-3,90]
# L = [23,45,23,67,3,90]

In [4]:
abs(-10)

10

In [5]:
abs(L)

TypeError: bad operand type for abs(): 'list'

In [6]:
for i in range(len(L)):
    L[i] = abs(L[i])
    
    

In [7]:
L

[23, 45, 23, 67, 3, 90]

In [10]:
import numpy as np
a = np.arange(-5,10)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [11]:
np.abs(a)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.log(5)

1.6094379124341003

In [13]:
import math
math.log(5)

1.6094379124341003

In [14]:

np.log([3,2,3,4,10])

array([1.09861229, 0.69314718, 1.09861229, 1.38629436, 2.30258509])

In [15]:

math.log([3,2,3,4,10])

TypeError: must be real number, not list

In [16]:
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [17]:
# min and max values
# sorting 
# index of min values


In [18]:
print(np.min(a))
print(np.max(a))
print(np.argmax(a)) # return the index of max value
print(np.argmin(a))

-5
9
14
0


In [19]:
np.sort(a)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [20]:


a = np.random.randint(10,30,(3,3))
a


array([[15, 22, 22],
       [10, 16, 17],
       [23, 25, 21]])

In [21]:
print(np.sum(a)) # Its an integer
print(np.sum(a,axis=0)) # Its numpy ndarray  dims 1
print(np.sum(a,axis=1))# Its numpy ndarray with dims 1
print(np.sum(a,axis=1,keepdims=True))
print(np.sum(a,axis=0,keepdims=True))

171
[48 63 60]
[59 43 69]
[[59]
 [43]
 [69]]
[[48 63 60]]


In [22]:

np.sum(a[:,0])

48

In [23]:
#own vectorize functions

In [25]:
def calculate(x):
    return x+(x*x)-5
calculate(2)




1

In [26]:
vcal = np.vectorize(calculate)
vcal([1,2,3,4])

array([-3,  1,  7, 15])

In [27]:
# a = [12,34,56,11]
# b = [13,37,12,5]
# [13,37,56,11]
def max2(v1,v2):
    if v1>v2:
        return v1
    else:
        return v2
max2(89,34)
vmax2 = np.vectorize(max2)

In [28]:
a = [12,34,56,11]
b = [13,37,12,5]
vmax2(a,b)

array([13, 37, 56, 11])

In [29]:
# stacking

In [30]:
a = np.arange(4)
b = np.arange(5,9)
np.hstack([a,b])

array([0, 1, 2, 3, 5, 6, 7, 8])

In [31]:
np.vstack([a,b])

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [32]:
a = np.arange(4)
b = np.arange(5,8)
np.hstack([a,b])

array([0, 1, 2, 3, 5, 6, 7])