Numpy

convert A list,tuple,dict in to Numpy array

How to generate array with in a range of values

arange

linespace

random.randint

basic arthimetc operators on numpy array

In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:

# How to slicing 
print(a[1:10])
print(a[1:5:2])
print(a[:])

[1 2 3 4 5 6 7 8 9]
[1 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
# Fancy Indexing or Boolean Indexing
print(a[a>5])

[6 7 8 9]


In [5]:
a.shape

(10,)

In [6]:
a.ndim

1

In [7]:
a2 = np.random.randint(10,30,(3,3))
a2

array([[16, 26, 29],
       [26, 19, 14],
       [23, 18, 21]])

In [8]:
print(a2.ndim)
print(a2.shape)

2
(3, 3)


In [9]:
for i in a2:
    print(i)
    break

[16 26 29]


In [10]:
for i in a2:
    for j in i:
        print(j,end=' ')
    print()

16 26 29 
26 19 14 
23 18 21 


In [11]:
print(a2[0],type(a2[0]),a2[0].shape)

[16 26 29] <class 'numpy.ndarray'> (3,)


In [12]:
print(a2[1:],type(a2[1:]),a2[1:].shape)

[[26 19 14]
 [23 18 21]] <class 'numpy.ndarray'> (2, 3)


In [13]:
# rows from 0  to 2
# columns from 0 to 2
# 1st row and second column
print(a2[1][2])
print(a2[1,2])

14
14


In [14]:
print(a2[1:3])

[[26 19 14]
 [23 18 21]]


In [15]:
print(a2[1:3,0:2])

[[26 19]
 [23 18]]


In [16]:
print(a2)

[[16 26 29]
 [26 19 14]
 [23 18 21]]


In [17]:
a3 = np.random.randint(10,100,(5,5,3))
a3

array([[[54, 28, 36],
        [90, 33, 11],
        [49, 35, 94],
        [44, 90, 49],
        [84, 61, 74]],

       [[15, 51, 99],
        [60, 80, 61],
        [17, 50, 46],
        [58, 21, 26],
        [96, 40, 48]],

       [[62, 43, 40],
        [89, 95, 66],
        [24, 35, 72],
        [22, 65, 32],
        [66, 79, 82]],

       [[74, 12, 85],
        [10, 12, 73],
        [26, 99, 38],
        [22, 22, 25],
        [78, 41, 47]],

       [[42, 13, 36],
        [90, 68, 50],
        [12, 47, 17],
        [12, 24, 46],
        [76, 91, 50]]])

In [18]:

print(a3[:2]) # indices - 0,1

[[[54 28 36]
  [90 33 11]
  [49 35 94]
  [44 90 49]
  [84 61 74]]

 [[15 51 99]
  [60 80 61]
  [17 50 46]
  [58 21 26]
  [96 40 48]]]


In [19]:

print(a3[1::2])

[[[15 51 99]
  [60 80 61]
  [17 50 46]
  [58 21 26]
  [96 40 48]]

 [[74 12 85]
  [10 12 73]
  [26 99 38]
  [22 22 25]
  [78 41 47]]]


In [20]:
print(a3[1::2,0:5:2])

[[[15 51 99]
  [17 50 46]
  [96 40 48]]

 [[74 12 85]
  [26 99 38]
  [78 41 47]]]


In [21]:
print(a3[1::2,0:5:2,2])

[[99 46 48]
 [85 38 47]]


In [22]:

a3==86

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [23]:
# Boolean Indexing
a3[a3==86]

array([], dtype=int32)

In [24]:
a3[a3>50]

array([54, 90, 94, 90, 84, 61, 74, 51, 99, 60, 80, 61, 58, 96, 62, 89, 95,
       66, 72, 65, 66, 79, 82, 74, 85, 73, 99, 78, 90, 68, 76, 91])

In [25]:
a3[(a3>50) & (a3<70)] #or -- |

array([54, 61, 51, 60, 61, 58, 62, 66, 65, 66, 68])

In [26]:
L = list(range(100))
# 0,1,2,3--- L[:]
# 1,2,3,4.... L[1:]
# 1,3,5,7,9,11,13 #L[1::2]
# 1,13,45,74,23,67 #

In [27]:

aL = np.array(L)
aL[[1,13,45,74,23,67]]


array([ 1, 13, 45, 74, 23, 67])

In [28]:
aL[[45,74,23,67,1,7,3]]

array([45, 74, 23, 67,  1,  7,  3])

In [29]:
a2

array([[16, 26, 29],
       [26, 19, 14],
       [23, 18, 21]])

In [30]:

a2[[1,2],[0,1]] # (1,0)(2,1)

array([26, 18])

In [31]:
print(a3[[1,2],[1,2],[1,2]])#(1,1,1)(2,2,2)
print(a3[1,1,1])
print(a3[2,2,2])


[80 72]
80
72


In [32]:
#Stastical functions

In [33]:
a = np.random.randint(20,30,5)
a

array([26, 20, 27, 20, 25])

In [34]:
print(np.mean(a))# avg
print(np.sum(a)/np.size(a))

23.6
23.6


In [35]:
# sorted a [23,24,25,27,29]
np.median(a)

25.0

In [36]:
print(np.quantile(a,0.25)) # Q1
print(np.quantile(a,0.5)) # Q2
print(np.quantile(a,0.75)) # Q3

20.0
25.0
26.0


In [37]:
#Logorithemic and Exponential

In [38]:

import numpy as np
print(np.log(2))# log with base e
print(np.log(np.exp(1)))

0.6931471805599453
1.0


In [39]:

print(np.log2(2))
print(np.log2(7))
print(np.log10(5))

1.0
2.807354922057604
0.6989700043360189


In [40]:
np.log(0+1)

0.0

In [41]:
print(np.log1p(2)) # np.log(1+2)
print(np.log1p(0)) # np.log(1+0)

1.0986122886681098
0.0


In [42]:
np.exp(1)

2.718281828459045

In [43]:
np.exp(2)

7.38905609893065

In [44]:
print(np.exp2(4))#2**4

16.0


In [46]:

print(np.expm1(2))# np.exp(2)-1
print(np.exp(2)-1)

6.38905609893065
6.38905609893065
